services:
  server:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test:
        [
          'CMD',
          'sh',
          '-c',
          'wget --spider --quiet http://localhost:8080/ || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:17
    container_name: wishes-postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local
