services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - sqlite-data:/app/data
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17
    container_name: wishes-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  sqlite-data:
    driver: local
  postgres_data:
    driver: local
