definitions:
  controllers.AdminLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.AdminLoginResponse:
    properties:
      admin:
        $ref: '#/definitions/models.Admin'
      token:
        type: string
    type: object
  controllers.AdminRegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.CreateWishRequest:
    properties:
      childName:
        type: string
      content:
        type: string
      gender:
        $ref: '#/definitions/models.Gender'
      grade:
        type: string
      photoUrl:
        type: string
    type: object
  controllers.GetWishesResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.Wish'
        type: array
      pagination:
        $ref: '#/definitions/controllers.Pagination'
    type: object
  controllers.Pagination:
    properties:
      pageIndex:
        type: integer
      pageSize:
        type: integer
      pageTotal:
        type: integer
      total:
        type: integer
    type: object
  controllers.UpdateWishDonorRequest:
    properties:
      address:
        type: string
      comment:
        type: string
      donorMobile:
        type: string
      donorName:
        type: string
    type: object
  controllers.UpdateWishRequest:
    properties:
      childName:
        type: string
      content:
        type: string
      gender:
        $ref: '#/definitions/models.Gender'
      grade:
        type: string
      photoUrl:
        type: string
    type: object
  controllers.WechatLoginRequest:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  controllers.WechatLoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  controllers.WechatUserInfoRequest:
    properties:
      avatarUrl:
        type: string
      nickName:
        type: string
    type: object
  models.Admin:
    description: 系统管理员信息
    properties:
      createdAt:
        type: integer
      deletedAt:
        type: integer
      id:
        type: integer
      password:
        type: string
      updatedAt:
        type: integer
      username:
        type: string
    type: object
  models.Gender:
    description: 用户性别类型
    enum:
    - male
    - female
    type: string
    x-enum-varnames:
    - Male
    - Female
  models.User:
    description: 微信小程序用户信息
    properties:
      avatarUrl:
        type: string
      createdAt:
        type: integer
      deletedAt:
        type: integer
      id:
        type: integer
      nickname:
        type: string
      updatedAt:
        type: integer
      wechatOpenId:
        type: string
      wechatUnionId:
        type: string
    type: object
  models.Wish:
    description: 儿童心愿信息
    properties:
      childName:
        type: string
      content:
        type: string
      createdAt:
        type: integer
      deletedAt:
        type: integer
      donor:
        $ref: '#/definitions/models.User'
      donorAddress:
        type: string
      donorComment:
        type: string
      donorId:
        type: integer
      donorMobile:
        type: string
      donorName:
        type: string
      gender:
        $ref: '#/definitions/models.Gender'
      grade:
        type: string
      id:
        type: integer
      isDone:
        type: boolean
      photoUrl:
        type: string
      updatedAt:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: 心愿墙公益项目API
  title: 心愿墙 API
  version: "1.0"
paths:
  /api/v1/admin/login:
    post:
      consumes:
      - application/json
      description: 管理员登录并获取认证令牌
      parameters:
      - description: 管理员登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.AdminLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.AdminLoginResponse'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 管理员登录
      tags:
      - 管理员
  /api/v1/admin/register:
    post:
      consumes:
      - application/json
      description: 创建新管理员账号
      parameters:
      - description: 管理员注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.AdminRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Admin'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties: true
            type: object
        "403":
          description: 禁止访问
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: 管理员注册
      tags:
      - 管理员
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 通过微信小程序临时登录凭证code进行登录
      parameters:
      - description: 微信登录请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.WechatLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.WechatLoginResponse'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 微信小程序登录
      tags:
      - 用户
  /api/v1/user/userinfo:
    put:
      consumes:
      - application/json
      description: 更新微信用户的昵称和头像
      parameters:
      - description: 微信用户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.WechatUserInfoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: 请求参数错误
          schema:
            additionalProperties: true
            type: object
        "401":
          description: 未授权
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: 更新微信用户信息
      tags:
      - 用户
  /api/v1/user/wishes:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户点亮的所有心愿
      parameters:
      - description: 页码，默认1
        in: query
        name: page-index
        type: integer
      - description: 每页数量，默认10
        in: query
        name: page-size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回用户点亮的心愿列表
          schema:
            $ref: '#/definitions/controllers.GetWishesResponse'
        "401":
          description: 用户未登录
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户点亮的心愿
      tags:
      - 用户
  /api/v1/wishes:
    get:
      consumes:
      - application/json
      description: 获取心愿列表，支持分页和过滤
      parameters:
      - description: 按心愿内容模糊搜索
        in: query
        name: content
        type: string
      - default: false
        description: 按完成状态过滤,默认为false
        in: query
        name: is-done
        type: boolean
      - default: 1
        description: 页码，默认1
        in: query
        name: page-index
        type: integer
      - default: 10
        description: 每页数量，默认10
        in: query
        name: page-size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 返回心愿列表和分页信息
          schema:
            $ref: '#/definitions/controllers.GetWishesResponse'
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取心愿列表
      tags:
      - 心愿
    post:
      consumes:
      - application/json
      description: 创建一个新的心愿
      parameters:
      - description: 心愿信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateWishRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 返回创建的心愿
          schema:
            $ref: '#/definitions/models.Wish'
        "400":
          description: 请求数据无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 创建新心愿
      tags:
      - 心愿
  /api/v1/wishes/{id}:
    delete:
      consumes:
      - application/json
      description: 删除心愿
      parameters:
      - description: 心愿ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功删除心愿
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求数据无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 删除心愿
      tags:
      - 心愿
    put:
      consumes:
      - application/json
      description: 更新心愿
      parameters:
      - description: 心愿ID
        in: path
        name: id
        required: true
        type: integer
      - description: 心愿信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateWishRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 返回更新后的心愿
          schema:
            $ref: '#/definitions/models.Wish'
        "400":
          description: 请求数据无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 更新心愿
      tags:
      - 心愿
  /api/v1/wishes/{id}/donor:
    put:
      consumes:
      - application/json
      description: 为心愿绑定捐赠者并标记为已完成
      parameters:
      - description: 心愿ID
        in: path
        name: id
        required: true
        type: integer
      - description: 捐赠者信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.UpdateWishDonorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 返回更新后的心愿
          schema:
            $ref: '#/definitions/models.Wish'
        "400":
          description: 请求数据无效
          schema:
            additionalProperties: true
            type: object
        "404":
          description: 心愿不存在
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 点亮心愿
      tags:
      - 心愿
swagger: "2.0"
